// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDARg3CM_HfpcLtslLcgzZ2xzgpUWCuHD0',
    appId: '1:866096151209:web:097ac4885b606f88ee87b8',
    messagingSenderId: '866096151209',
    projectId: 'notification-app-46cff',
    authDomain: 'notification-app-46cff.firebaseapp.com',
    storageBucket: 'notification-app-46cff.firebasestorage.app',
    measurementId: 'G-1NLR4CB3Q7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADtrlLREco3GBvMkAIxbwIc6f5gKhKwsM',
    appId: '1:866096151209:android:3bed550205f4181fee87b8',
    messagingSenderId: '866096151209',
    projectId: 'notification-app-46cff',
    storageBucket: 'notification-app-46cff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw0hOhimWV5RUuTBUVPa_CGj6mpip1rsc',
    appId: '1:866096151209:ios:89ecdaac942e087aee87b8',
    messagingSenderId: '866096151209',
    projectId: 'notification-app-46cff',
    storageBucket: 'notification-app-46cff.firebasestorage.app',
    iosBundleId: 'com.example.notificationDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw0hOhimWV5RUuTBUVPa_CGj6mpip1rsc',
    appId: '1:866096151209:ios:89ecdaac942e087aee87b8',
    messagingSenderId: '866096151209',
    projectId: 'notification-app-46cff',
    storageBucket: 'notification-app-46cff.firebasestorage.app',
    iosBundleId: 'com.example.notificationDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDARg3CM_HfpcLtslLcgzZ2xzgpUWCuHD0',
    appId: '1:866096151209:web:30b7f9612d9e7438ee87b8',
    messagingSenderId: '866096151209',
    projectId: 'notification-app-46cff',
    authDomain: 'notification-app-46cff.firebaseapp.com',
    storageBucket: 'notification-app-46cff.firebasestorage.app',
    measurementId: 'G-B6WD8PBW3X',
  );
}
